# Generated by Django 5.0.3 on 2024-04-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mtplnewapp', '0006_remove_document_employee_remove_document_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document_no', models.CharField(max_length=50)),
                ('order_serial_no', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('material_code', models.CharField(max_length=50)),
                ('material_description', models.TextField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejection_reason', models.CharField(max_length=50)),
                ('reason_for_rejection', models.TextField()),
                ('file_upload', models.FileField(upload_to='uploads/')),
                ('man_hours_wasted', models.DecimalField(decimal_places=2, max_digits=5)),
                ('machine_hours_wasted', models.DecimalField(decimal_places=2, max_digits=5)),
                ('information_to_buyer', models.TextField()),
                ('status', models.CharField(default='0', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mtplnewapp.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtplnewapp.project')),
            ],
        ),
    ]
