# Generated by Django 5.0.3 on 2024-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(default='0', max_length=50),
        ),
    ]
