# Generated by Django 5.0.3 on 2024-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtplnew_dataentry',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtplnew_dataentry',
            name='ncraised',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
