# Generated by Django 5.0.3 on 2024-04-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0014_mtplnew_dataentry_approval_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtplnew_dataentry',
        ),
    ]
