# Generated by Django 5.0.3 on 2024-04-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtplnew_dataentry',
        ),
    ]
