# Generated by Django 5.0.3 on 2024-04-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtplnew_dataentry',
            name='ncraised',
            field=models.CharField(max_length=10),
        ),
    ]
