# Generated by Django 5.0.3 on 2024-04-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0019_alter_mtplnew_dataentry_ncraised'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtplnew_dataentry',
        ),
    ]
