# Generated by Django 5.0.3 on 2024-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0023_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtplnew_dataentry',
            name='nc_raised',
            field=models.CharField(max_length=3),
        ),
    ]
