# Generated by Django 5.0.3 on 2024-04-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0024_alter_mtplnew_dataentry_nc_raised'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtplnew_dataentry',
        ),
    ]
