# Generated by Django 5.0.3 on 2024-04-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0028_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtplnew_dataentry',
            name='ncraised',
        ),
    ]
