# Generated by Django 5.0.3 on 2024-04-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0029_remove_mtplnew_dataentry_ncraised'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtplnew_dataentry',
        ),
    ]
