# Generated by Django 5.0.3 on 2024-04-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0031_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtplnew_dataentry',
        ),
    ]
