# Generated by Django 5.0.3 on 2024-04-26 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0033_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtplnew_dataentry',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
