# Generated by Django 5.0.3 on 2024-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0034_alter_mtplnew_dataentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtplnew_dataentry',
            name='qty',
            field=models.CharField(max_length=1000),
        ),
    ]
