# Generated by Django 5.0.3 on 2024-04-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtplnewapp', '0035_alter_mtplnew_dataentry_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtplnew_dataentry',
        ),
    ]
